version: "3.8"

services:
  mongodb:
    image: docker.io/library/mongo:7
    container_name: yugioh-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: yugioh-collection
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: