services:
  db:
    image: docker.io/library/mongo:7
    container_name: yugioh-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: yugioh-collection
    volumes:
      - mongodb_data:/data/db

  backend:
    build: ./backend/Containerfile
    depends-on:
      - mongodb
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://db:27017/yugioh-collection

volumes:
  mongodb_data: